/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['@import url(https://fonts.googleapis.com/css?family=Roboto:400,300,600,400italic);*{margin:0;padding:0;box-sizing:border-box;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;-webkit-font-smoothing:antialiased;-moz-font-smoothing:antialiased;-o-font-smoothing:antialiased;font-smoothing:antialiased;text-rendering:optimizeLegibility}body{font-family:Roboto,Helvetica,Arial,sans-serif;font-weight:100;font-size:12px;line-height:30px;color:#777}body,html{height:100%;font-family:Arial,Helvetica,sans-serif}body{position:fixed;width:100%;height:100%}a.active{background-color:gray}.container{max-width:400px;width:100%;margin:0 auto;position:relative}#contact{background:#f9f9f9;padding:25px;margin:150px 0;box-shadow:0 0 20px 0 rgba(0,0,0,.2),0 5px 5px 0 rgba(0,0,0,.24)}#contact h3{display:block;font-size:30px;font-weight:300;margin-bottom:10px}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc3BsaW5jb2RlL0RldmVsb3AvbWVldHVwLzIwMTcvanVseS9uZy9hbmd1bGFyLXN0YXJ0ZXIvc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcy5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9zcGxpbmNvZGUvRGV2ZWxvcC9tZWV0dXAvMjAxNy9qdWx5L25nL2FuZ3VsYXItc3RhcnRlci9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
